---

Server:
  grpc:
    port: 50051
    host: "localhost"
    production: false
  http:
    port: 8080
    host: "localhost"
    production: true
datasource:
  redis:
    enabled: false
    host: "localhost"
    port: 6379
    password: ""
    db: 0
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "salam"
    database: "greeter"
observability:
  tracing:
    enabled: true
    zipkin:
      url: "http://localhost:9411/api/v2/spans"
      service_name: "greeter"
  metrics:
    prometheus:
      port: 9090
      host: "localhost"
      path: "/metrics"
  logging:
    level: "debug"

